version: '3.8'

services:
  vn-learning-db:
    image: mariadb:11
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - vn_learning_db:/var/lib/mysql
    ports:
      - "3306:3306"

  vn-learning-api:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - vn-learning-db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  vn_learning_db:
